"use strict";
const $ = id => document.getElementById(id);
let token = sessionStorage.getItem("chili-token") || "", state = null, page = "player", busy = false, polling = false, online = false;
let queueRows = [], queueRevision = -1, libraryRows = [], albumRows = [], libraryOffset = 0, inAlbum = false, searchSequence = 0;
let coverKey = "", coverUrl = "", audioKey = "", audioSync = false, audioFallback = false, seeking = false, volumeDragging = false, toastTimer, lastPositionSend = 0, seekRevision = -1;
const audio = $("audio");
const nativePhoneVolume = /iPhone|iPad|iPod/.test(navigator.userAgent) || navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1;
function icon(name){const svg=document.createElementNS("http://www.w3.org/2000/svg","svg"), use=document.createElementNS(svg.namespaceURI,"use");use.setAttribute("href","#icon-"+name);svg.append(use);return svg;}
function setIcon(button,name){button.replaceChildren(icon(name));}
function clock(value){value=Math.max(0,Math.floor(Number(value)||0));return Math.floor(value/60)+":"+String(value%60).padStart(2,"0");}
function toast(message){$("toast").textContent=message;$("toast").hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").hidden=true,4200);}
function colors(data){if(!data)return;Object.entries(data).forEach(([name,value])=>document.documentElement.style.setProperty("--"+name.replace(/[A-Z]/g,c=>"-"+c.toLowerCase()),value));document.documentElement.style.colorScheme=state?.dark?"dark":"light";document.querySelector('meta[name="theme-color"]').content=data.bg;}
async function api(path,body,signal){const headers={};if(token)headers["X-Chili-Token"]=token;if(body!==undefined)headers["Content-Type"]="application/json";const response=await fetch(path,{method:body===undefined?"GET":"POST",headers,body:body===undefined?undefined:JSON.stringify(body),signal});let data;try{data=await response.json();}catch{throw new Error("连接未完成，请重试");}if(!response.ok){if(response.status===401&&path!=="/api/pair")unpair();throw new Error(data.error||"操作未完成");}return data;}
function unpair(){token="";sessionStorage.removeItem("chili-token");stopAudio();$("pair").hidden=false;$("app").hidden=true;$("logout").hidden=true;$("connection").textContent="未配对";$("connection").className="connection";state=null;}
function stopAudio(){audioSync=true;audio.pause();audio.removeAttribute("src");audio.load();audioKey="";audioSync=false;}
async function poll(){if(!token||polling)return;polling=true;try{const data=await api("/api/state");online=true;render(data);if(page==="queue"&&queueRevision!==data.revision)await loadQueue(false);}catch(error){online=false;if(token){$("connection").textContent="连接中断";$("connection").className="connection";audio.pause();} }finally{polling=false;}}
async function command(action,extra={}){if(busy)return;busy=true;try{const data=await api("/api/command",{action,...extra});render(data);if(page==="queue"&&queueRevision!==data.revision)await loadQueue(false);return data;}catch(error){toast(error.message);await poll();}finally{busy=false;}}
function render(data){state=data;colors(data.colors);$("pair").hidden=true;$("app").hidden=false;$("logout").hidden=false;$("connection").textContent="已连接";$("connection").className="connection connected";$("theme-name").textContent=data.theme;$("title").textContent=data.current?.title||"尚未播放";$("artist").textContent=data.current?[data.current.artist,data.current.album,data.current.preview?"试听":""].filter(Boolean).join(" · "):"从曲库选择一首歌曲";$("favorite").classList.toggle("active",!!data.current?.favorite);$("favorite").disabled=!data.current;$("play-button").setAttribute("aria-label",data.playing?"暂停":"播放");setIcon($("play-button"),data.playing?"pause":"play");$("seek").max=Math.max(1,data.duration);$("seek").disabled=!data.current||!data.duration;if(!seeking){$("seek").value=data.position;$("position").textContent=clock(data.position);}$("duration").textContent=clock(data.duration);if(!volumeDragging){$("volume").value=data.volume;$("volume-value").textContent=Math.round(data.volume);}$("volume").hidden=data.output==="phone"&&data.phoneOwner&&nativePhoneVolume;if($("volume").hidden)$("volume-value").textContent="使用手机音量键";setIcon($("mute"),data.mute?"mute":"volume");$("mute").setAttribute("aria-label",data.mute?"取消静音":"静音");const mode=data.mode===3?"shuffle":data.mode===0?"arrow":"repeat";$("mode").querySelector("use").setAttribute("href","#icon-"+mode);$("repeat-one").hidden=data.mode!==2;$("mode").setAttribute("aria-label",data.modeText+"，点击切换");$("mode").title=data.modeText;$("shuffle-button").classList.toggle("active",data.mode===3);$("computer-output").classList.toggle("active",data.output==="computer");$("phone-output").classList.toggle("active",data.output==="phone"&&data.phoneOwner);$("computer-output").setAttribute("aria-pressed",String(data.output==="computer"));$("phone-output").setAttribute("aria-pressed",String(data.output==="phone"&&data.phoneOwner));$("output-hint").textContent=data.output==="computer"?"音乐由电脑播放":data.phoneOwner?"音乐由这台手机播放 · 电脑需保持开启":"音乐正由另一台手机播放";$("source").querySelector('[value="server"]').disabled=!data.server;if(!data.server&&$("source").value==="server")$("source").value=data.netease?"netease":"local";if(data.current?.key!==coverKey){coverKey=data.current?.key||"";loadCover(coverKey);}renderRows($("next-list"),data.next,"preview");syncAudio(data);syncLyrics(data);}
async function loadCover(key){$("cover").hidden=true;$("cover-empty").hidden=false;if(coverUrl){URL.revokeObjectURL(coverUrl);coverUrl="";}if(!key)return;try{const response=await fetch("/api/cover?key="+encodeURIComponent(key),{headers:{"X-Chili-Token":token}});if(!response.ok)return;const blob=await response.blob();if(key!==coverKey)return;coverUrl=URL.createObjectURL(blob);$("cover").src=coverUrl;$("cover").hidden=false;$("cover-empty").hidden=true;}catch{}}
function rowButton(label,action){const button=document.createElement("button");button.textContent=label;button.addEventListener("click",action);return button;}
function renderRows(container,rows,kind){container.replaceChildren();if(!rows.length){const empty=document.createElement("div");empty.className="empty";empty.textContent=kind==="preview"?"队列中没有下一首":kind==="queue"?"播放队列还是空的":"没有找到歌曲";container.append(empty);return;}for(const track of rows){const row=document.createElement("div");row.className="song-row"+(state?.current?.key===track.key?" current":"");const main=document.createElement("button");main.className="song-main";main.title=track.title;const thumb=document.createElement("span");thumb.className="thumb";thumb.append(icon(track.index===state?.current?.index&&kind!=="library"?"play":"note"));const copy=document.createElement("span");copy.className="song-copy";const title=document.createElement("span"),artist=document.createElement("span");title.className="song-title";artist.className="song-artist";title.textContent=track.title;artist.textContent=track.artist||track.album||"未知歌手";copy.append(title,artist);main.append(thumb,copy);main.addEventListener("click",()=>kind==="album"?openAlbum(track):command(kind==="library"?"play-track":"queue-play",kind==="library"?{key:track.key}:{index:track.index,revision:state.revision}));row.append(main);if(track.duration){const time=document.createElement("span");time.className="song-duration";time.textContent=clock(track.duration);row.append(time);}if(kind!=="preview"){const more=document.createElement("button");more.className="icon";more.setAttribute("aria-label",track.title+"的操作");more.append(icon("more"));const actions=document.createElement("div");actions.className="row-actions";actions.hidden=true;more.addEventListener("click",()=>actions.hidden=!actions.hidden);if(kind==="queue"){actions.append(rowButton("上移",()=>command("queue-move",{index:track.index,to:track.index-1,revision:queueRevision})),rowButton("下移",()=>command("queue-move",{index:track.index,to:track.index+1,revision:queueRevision})),rowButton("移除",()=>command("queue-remove",{index:track.index,revision:queueRevision})));actions.children[0].disabled=track.index===0;actions.children[1].disabled=track.index>=state.queueTotal-1;}else if(kind==="library"){actions.append(rowButton("加入队列",()=>command("add",{key:track.key})),rowButton("下一首播放",()=>command("add-next",{key:track.key})));}else actions.append(rowButton("查看歌曲",()=>openAlbum(track)));row.append(more,actions);}container.append(row);}}
function switchPage(tab){page=tab;document.querySelectorAll(".page").forEach(p=>p.hidden=p.id!==tab);document.querySelectorAll("[data-tab]").forEach(b=>{b.classList.toggle("active",b.dataset.tab===tab);if(b.dataset.tab===tab)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current");});if(tab==="queue")loadQueue(false);if(tab==="library"&&!libraryRows.length&&!albumRows.length)search(false);window.scrollTo({top:0,behavior:"instant"});}
async function loadQueue(append){try{const data=await api("/api/queue?offset="+(append?queueRows.length:0));if(append&&queueRevision!==data.revision)return loadQueue(false);queueRevision=data.revision;queueRows=append?queueRows.concat(data.tracks):data.tracks;$("queue-count").textContent=data.total+" 首";$("queue-more").hidden=queueRows.length>=data.total;renderRows($("queue-list"),queueRows,"queue");}catch(error){toast(error.message);}}
async function search(append){const sequence=++searchSequence, offset=append?libraryOffset:0;inAlbum=false;$("album-back").hidden=true;$("library-title").textContent=$("search").value?"搜索结果":$("source").value==="netease"?({newest:"网易云新碟",recent:"最近播放",favorites:"网易云收藏",daily:"每日推荐"}[$("library-view").value]||"歌曲"):$("source").value==="server"?($("library-view").value==="recent"?"最近播放":"最近添加"):"歌曲";$("library-more").disabled=true;try{const data=await api("/api/library?source="+encodeURIComponent($("source").value)+"&view="+encodeURIComponent($("library-view").value)+"&query="+encodeURIComponent($("search").value.trim())+"&offset="+offset);if(sequence!==searchSequence)return;libraryRows=append?libraryRows.concat(data.tracks):data.tracks;albumRows=append?albumRows.concat(data.albums):data.albums;libraryOffset=offset+50;$("library-more").hidden=!data.more;renderRows($("library-list"),albumRows.length?albumRows:libraryRows,albumRows.length?"album":"library");}catch(error){toast(error.message);}finally{$("library-more").disabled=false;}}
async function openAlbum(album){try{const data=await api("/api/album?key="+encodeURIComponent(album.key));inAlbum=true;$("album-back").hidden=false;$("library-more").hidden=true;$("library-title").textContent=data.title;renderRows($("library-list"),data.tracks,"library");}catch(error){toast(error.message);}}
function audioFormat(track){const type={mp3:"audio/mpeg",flac:"audio/flac",m4a:"audio/mp4",aac:"audio/mp4",wav:"audio/wav",ogg:"audio/ogg",opus:"audio/ogg"}[track.format.toLowerCase()];return type&&audio.canPlayType(type)?"original":"mp3";}
function syncAudio(data){if(data.output!=="phone"||!data.phoneOwner){if(audioKey)stopAudio();return;}audio.volume=Math.max(0,Math.min(1,data.volume/100));audio.muted=data.mute;if(!data.current){stopAudio();return;}if(audioKey!==data.current.key){audioKey=data.current.key;audioFallback=false;audio.src="/api/audio?key="+encodeURIComponent(audioKey)+"&format="+audioFormat(data.current);audio.load();}if(audio.readyState>=1&&!seeking&&seekRevision!==data.seekRevision)audio.currentTime=data.position;seekRevision=data.seekRevision;audioSync=true;if(data.playing&&audio.paused)audio.play().catch(()=>toast("点播放按钮开始手机播放"));else if(!data.playing&&!audio.paused)audio.pause();audioSync=false;if("mediaSession" in navigator&&"MediaMetadata" in window){navigator.mediaSession.metadata=new MediaMetadata({title:data.current.title,artist:data.current.artist,album:data.current.album});navigator.mediaSession.playbackState=data.playing?"playing":"paused";}}
$("pair-form").addEventListener("submit",async event=>{event.preventDefault();$("pair-button").disabled=true;$("pair-error").textContent="";try{const data=await api("/api/pair",{code:$("code").value.trim()});token=data.token;sessionStorage.setItem("chili-token",token);await poll();}catch(error){$("pair-error").textContent=error.message;}finally{$("pair-button").disabled=false;}});
$("logout").addEventListener("click",async()=>{try{await api("/api/logout",{});}catch{}unpair();});document.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>switchPage(b.dataset.tab)));document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>command(b.dataset.action)));$("play-button").addEventListener("click",()=>{if(state?.output==="phone"&&state.phoneOwner&&audio.paused){audio.play().catch(()=>toast("音频无法播放，请换用支持此格式的浏览器"));command("play");}else command("toggle");});$("phone-output").addEventListener("click",()=>command("output-phone"));$("computer-output").addEventListener("click",()=>command("output-computer",state?.phoneOwner?{value:audio.currentTime}:{}));$("favorite").addEventListener("click",()=>command("favorite"));$("mode").addEventListener("click",()=>command("mode"));$("shuffle-button").addEventListener("click",async()=>{const desired=state?.mode===3?0:3;for(let i=0;i<4&&state?.mode!==desired;i++)await command("mode");});$("mute").addEventListener("click",()=>command("mute"));$("volume").addEventListener("input",()=>{volumeDragging=true;$("volume-value").textContent=$("volume").value;if(state?.phoneOwner)audio.volume=Number($("volume").value)/100;});$("volume").addEventListener("change",()=>{volumeDragging=false;command("volume",{value:Number($("volume").value)});});$("seek").addEventListener("input",()=>{seeking=true;$("position").textContent=clock($("seek").value);});$("seek").addEventListener("change",()=>{const position=Number($("seek").value);if(state?.phoneOwner&&audio.readyState>=1)audio.currentTime=position;seeking=false;command("seek",{value:position});});$("show-queue").addEventListener("click",()=>switchPage("queue"));$("queue-more").addEventListener("click",()=>loadQueue(true));$("search-form").addEventListener("submit",event=>{event.preventDefault();search(false);});$("source").addEventListener("change",()=>{updateLibraryView();search(false);});$("library-view").addEventListener("change",()=>search(false));$("album-back").addEventListener("click",()=>search(false));$("library-more").addEventListener("click",()=>search(true));
audio.addEventListener("loadedmetadata",()=>{if(state?.phoneOwner&&Math.abs(audio.currentTime-state.position)>1)audio.currentTime=state.position;});audio.addEventListener("timeupdate",()=>{if(state?.output!=="phone"||!state.phoneOwner)return;if(!seeking){$("seek").value=audio.currentTime;$("position").textContent=clock(audio.currentTime);}if(Date.now()-lastPositionSend>2500&&!audio.paused){lastPositionSend=Date.now();api("/api/command",{action:"phone-position",key:audioKey,value:audio.currentTime}).catch(()=>{});}});audio.addEventListener("ended",()=>command("phone-ended",{key:audioKey}));audio.addEventListener("error",()=>{if(audioKey&&!audioFallback&&!state?.current?.local&&audio.src.includes("format=original")){audioFallback=true;audio.src="/api/audio?key="+encodeURIComponent(audioKey)+"&format=mp3";audio.load();if(state?.playing)audio.play().catch(()=>toast("点播放按钮开始手机播放"));return;}if(audioKey){toast("此音频无法在手机播放，请检查格式或服务端转码设置");command("pause");}});if("mediaSession" in navigator){for(const [name,action]of Object.entries({play:"play",pause:"pause",nexttrack:"next",previoustrack:"previous"}))try{navigator.mediaSession.setActionHandler(name,()=>command(action));}catch{}}
document.addEventListener("visibilitychange",()=>{if(!document.hidden)poll();});setInterval(()=>{if(!document.hidden||state?.phoneOwner)poll();},1250);api("/api/info").then(data=>{colors(data.colors);document.documentElement.style.colorScheme=data.dark?"dark":"light";$("theme-name").textContent=data.theme;}).catch(()=>{});if(token)poll();

let lyricsOpen=false, lyricsStamp="", lyricRows=[], lyricActive=-1, lyricManualUntil=0, lyricLoading=false, lyricsKey="";
function updateLibraryView(){const source=$("source").value;$("library-view").hidden=!["server","netease"].includes(source);for(const option of $("library-view").options)option.disabled=["favorites","daily"].includes(option.value)&&source!=="netease";if($("library-view").selectedOptions[0].disabled)$("library-view").value="newest";}
function toggleLyrics(){lyricsOpen=!lyricsOpen;document.body.classList.toggle("lyrics-mode",lyricsOpen);const heading=document.querySelector(".song-heading");if(lyricsOpen)$("phone-lyrics").before(heading);else $("phone-lyrics").after(heading);$("phone-lyrics").hidden=!lyricsOpen;$("artwork").hidden=lyricsOpen;$("lyrics-toggle").textContent=lyricsOpen?"封面":"歌词";$("lyrics-toggle").setAttribute("aria-pressed",String(lyricsOpen));if(lyricsOpen){lyricsStamp="";syncLyrics(state);}}
$("lyrics-toggle").addEventListener("click",toggleLyrics);$("artwork").addEventListener("click",toggleLyrics);$("artwork").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();toggleLyrics();}});
$("lyrics-translation").addEventListener("change",()=>$("lyrics-lines").classList.toggle("no-translation",!$("lyrics-translation").checked));
$("lyrics-lines").addEventListener("wheel",()=>{lyricManualUntil=Date.now()+5000;$("lyrics-follow").hidden=false;},{passive:true});$("lyrics-lines").addEventListener("touchstart",()=>{lyricManualUntil=Date.now()+5000;$("lyrics-follow").hidden=false;},{passive:true});$("lyrics-follow").addEventListener("click",()=>{lyricManualUntil=0;lyricActive=-1;positionLyrics();});
async function syncLyrics(data){if(!lyricsOpen||!data)return;if((data.current?.key||"")!==lyricsKey){lyricsKey=data.current?.key||"";lyricRows=[];lyricActive=-1;lyricManualUntil=0;$("lyrics-lines").replaceChildren();$("lyrics-status").textContent="正在加载歌词…";}const stamp=(data.current?.key||"")+":"+data.lyricsRevision;if(stamp!==lyricsStamp&&!lyricLoading){lyricLoading=true;try{const lyrics=await api("/api/lyrics");if(lyrics.key!==(state?.current?.key||""))return;lyricsStamp=lyrics.key+":"+lyrics.revision;lyricRows=lyrics.lines;lyricActive=-1;$("lyrics-status").textContent=lyrics.status;const box=$("lyrics-lines");box.replaceChildren();if(!lyricRows.length){const empty=document.createElement("p");empty.className="empty";empty.textContent=lyrics.status;box.append(empty);}for(const line of lyricRows){const button=document.createElement("button");button.className="lyric-line";const words=document.createElement("span");words.textContent=line.text;button.append(words);if(line.translation){const translation=document.createElement("small");translation.textContent=line.translation;button.append(translation);}button.disabled=line.time===null;button.addEventListener("click",()=>{lyricManualUntil=0;command("seek",{value:Math.max(0,line.time-(state?.lyricOffset||0))});});box.append(button);}}catch{}finally{lyricLoading=false;}}positionLyrics();}
function positionLyrics(){if(!lyricsOpen||!state)return;const position=state.phoneOwner&&audio.readyState?audio.currentTime:state.position;let active=-1;for(let i=0;i<lyricRows.length;i++)if(lyricRows[i].time!==null&&lyricRows[i].time<=position+(state.lyricOffset||0))active=i;const rows=$("lyrics-lines").querySelectorAll(".lyric-line");if(active!==lyricActive){if(rows[lyricActive])rows[lyricActive].classList.remove("active");lyricActive=active;if(rows[active])rows[active].classList.add("active");}if(Date.now()>=lyricManualUntil){$("lyrics-follow").hidden=true;const row=rows[Math.max(0,active)],box=$("lyrics-lines");if(row){const target=row.offsetTop-box.clientHeight/2+row.clientHeight/2;if(Math.abs(box.scrollTop-target)>3)box.scrollTo({top:target,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}}}
audio.addEventListener("timeupdate",positionLyrics);updateLibraryView();
