global using System.IO;
global using System.Net.Http;
global using Application = System.Windows.Application;
global using Window = System.Windows.Window;
global using Button = System.Windows.Controls.Button;
global using TextBox = System.Windows.Controls.TextBox;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using ListBox = System.Windows.Controls.ListBox;
global using Orientation = System.Windows.Controls.Orientation;
global using MessageBox = System.Windows.MessageBox;
global using Point = System.Windows.Point;
global using Color = System.Windows.Media.Color;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using UserControl = System.Windows.Controls.UserControl;
global using Binding = System.Windows.Data.Binding;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using DataObject = System.Windows.DataObject;
global using DragDropEffects = System.Windows.DragDropEffects;
