using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Shell;

namespace ChiliMusic;

internal sealed class ImmersiveWindow : Window
{
    internal ImmersiveWindow(PlayerViewModel vm)
    {
        Title = "chilimusic · 正在播放"; Width = Math.Min(1100, SystemParameters.WorkArea.Width - 20); Height = Math.Min(760, SystemParameters.WorkArea.Height - 20); MinWidth = 860; MinHeight = 600;
        DataContext = vm; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; WindowStartupLocation = WindowStartupLocation.CenterScreen; ResizeMode = ResizeMode.CanResize;
        SetResourceReference(ForegroundProperty, "TextBrush"); SetResourceReference(FontFamilyProperty, "AppFont");
        WindowChrome.SetWindowChrome(this, new() { CaptionHeight = 44, ResizeBorderThickness = new Thickness(6), GlassFrameThickness = new Thickness(0), UseAeroCaptionButtons = false });
        var frame = new Border { CornerRadius = new CornerRadius(10), BorderThickness = new Thickness(1) }; frame.SetResourceReference(Border.BackgroundProperty, "BackgroundBrush"); frame.SetResourceReference(Border.BorderBrushProperty, "BorderBrush");
        var root = new Grid(); frame.Child = root; Content = frame;
        var backdrop = new System.Windows.Controls.Image { Stretch = Stretch.UniformToFill, Opacity = .6, Effect = new BlurEffect { Radius = 65, RenderingBias = RenderingBias.Performance }, IsHitTestVisible = false }; backdrop.SetBinding(System.Windows.Controls.Image.SourceProperty, new Binding("Cover")); root.Children.Add(backdrop);
        var shade = new Border { IsHitTestVisible = false }; shade.SetResourceReference(Border.BackgroundProperty, "BackgroundBrush"); root.Children.Add(shade);
        void UpdateTheme() => shade.Opacity = Theme.IsDark ? .58 : .84;
        Theme.Updated += UpdateTheme; UpdateTheme();
        var layout = new Grid(); layout.RowDefinitions.Add(new() { Height = new GridLength(44) }); layout.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); layout.RowDefinitions.Add(new() { Height = new GridLength(120) }); root.Children.Add(layout);
        var header = new DockPanel { Margin = new Thickness(18, 0, 12, 0) };
        var close = MakeIcon("\uE8BB", "关闭播放页", Close, 34, 13); var minimize = MakeIcon("\uE921", "最小化", () => WindowState = WindowState.Minimized, 34, 12); var collapse = MakeIcon("\uE70D", "收起播放页", Close, 34, 14);
        foreach (var button in new[] { close, minimize, collapse }) { WindowChrome.SetIsHitTestVisibleInChrome(button, true); DockPanel.SetDock(button, Dock.Right); header.Children.Add(button); }
        var brand = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center }; brand.Children.Add(new System.Windows.Controls.Image { Source = new System.Windows.Media.Imaging.BitmapImage(new Uri("pack://application:,,,/Resources/chilimusic.png")), Width = 19, Height = 19, Margin = new Thickness(0, 0, 9, 0) }); brand.Children.Add(new TextBlock { Text = "chilimusic", FontSize = 14, FontWeight = FontWeights.Medium, VerticalAlignment = VerticalAlignment.Center }); header.Children.Add(brand); layout.Children.Add(header);
        var content = new Grid { Margin = new Thickness(42, 18, 42, 4) }; content.ColumnDefinitions.Add(new() { Width = new GridLength(.43, GridUnitType.Star) }); content.ColumnDefinitions.Add(new() { Width = new GridLength(.57, GridUnitType.Star) }); Grid.SetRow(content, 1); layout.Children.Add(content);
        var record = new StackPanel { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(0, 0, 42, 0) };
        var art = new Grid { Width = 360, Height = 360 }; var note = new TextBlock { Text = "♪", FontSize = 100, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center }; note.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); art.Children.Add(note);
        var image = new Border { CornerRadius = new CornerRadius(8) }; var brush = new ImageBrush { Stretch = Stretch.UniformToFill }; BindingOperations.SetBinding(brush, ImageBrush.ImageSourceProperty, new Binding("Cover") { Source = vm }); image.Background = brush; art.Children.Add(image);
        var artwork = new Border { CornerRadius = new CornerRadius(8), BorderThickness = new Thickness(1), Child = new Viewbox { Child = art }, HorizontalAlignment = HorizontalAlignment.Left }; artwork.SetResourceReference(Border.BackgroundProperty, "SurfaceBrush"); artwork.SetResourceReference(Border.BorderBrushProperty, "BorderBrush"); record.Children.Add(artwork);
        var title = new TextBlock { FontSize = 28, FontWeight = FontWeights.SemiBold, Margin = new Thickness(0, 20, 0, 7), TextWrapping = TextWrapping.Wrap, TextTrimming = TextTrimming.CharacterEllipsis, MaxHeight = 78 }; title.SetBinding(TextBlock.TextProperty, new Binding("Title")); title.SetBinding(ToolTipProperty, new Binding("Title")); record.Children.Add(title);
        var artist = new TextBlock { FontSize = 16, TextTrimming = TextTrimming.CharacterEllipsis, Margin = new Thickness(0, 0, 0, 5) }; artist.SetBinding(TextBlock.TextProperty, new Binding("Artist")); record.Children.Add(artist);
        var album = new TextBlock { FontSize = 12, TextTrimming = TextTrimming.CharacterEllipsis }; album.SetBinding(TextBlock.TextProperty, new Binding("Album")); album.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); record.Children.Add(album);
        var details = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0, 13, 0, 0) }; var favorite = MakeIcon("", "收藏 / 取消收藏", null, 34, 24); favorite.FontFamily = new System.Windows.Media.FontFamily("Segoe UI Symbol"); favorite.Command = vm.FavoriteCommand; favorite.SetBinding(ContentProperty, new Binding("FavoriteGlyph")); favorite.SetResourceReference(ForegroundProperty, "AccentBrush"); details.Children.Add(favorite);
        var divider = new Border { Width = 1, Height = 20, Margin = new Thickness(12, 0, 15, 0), VerticalAlignment = VerticalAlignment.Center }; divider.SetResourceReference(Border.BackgroundProperty, "BorderBrush"); details.Children.Add(divider);
        var format = new TextBlock { FontSize = 11 }; format.SetBinding(TextBlock.TextProperty, new Binding("Current.Format")); var badge = new Border { Child = format, BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(3), Padding = new Thickness(7, 3, 7, 3), VerticalAlignment = VerticalAlignment.Center }; badge.SetResourceReference(Border.BorderBrushProperty, "AccentBrush"); badge.SetBinding(ToolTipProperty, new Binding("AudioInfo")); details.Children.Add(badge); record.Children.Add(details); content.Children.Add(record);
        void FitArtwork() { double size = Math.Clamp(Math.Min(record.ActualWidth, content.ActualHeight - 174), 120, 360); artwork.Width = artwork.Height = size; }
        content.SizeChanged += (_, _) => FitArtwork(); record.SizeChanged += (_, _) => FitArtwork();
        var words = new Grid(); words.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); words.RowDefinitions.Add(new() { Height = new GridLength(38) }); words.Children.Add(new LyricsView(vm, true)); var tools = new LyricsToolbar(vm, true) { HorizontalAlignment = HorizontalAlignment.Right }; Grid.SetRow(tools, 1); words.Children.Add(tools); Grid.SetColumn(words, 1); content.Children.Add(words);
        var footer = new Grid { Margin = new Thickness(40, 10, 40, 18) }; footer.RowDefinitions.Add(new() { Height = new GridLength(25) }); footer.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); Grid.SetRow(footer, 2); layout.Children.Add(footer);
        var progress = new Grid(); progress.ColumnDefinitions.Add(new() { Width = new GridLength(44) }); progress.ColumnDefinitions.Add(new() { Width = new GridLength(1, GridUnitType.Star) }); progress.ColumnDefinitions.Add(new() { Width = new GridLength(44) }); footer.Children.Add(progress);
        var elapsed = Time("PositionText", HorizontalAlignment.Left); var duration = Time("DurationText", HorizontalAlignment.Right); progress.Children.Add(elapsed); Grid.SetColumn(duration, 2); progress.Children.Add(duration);
        var seek = new Slider { Minimum = 0, IsMoveToPointEnabled = true, Margin = new Thickness(8, 0, 8, 0), VerticalAlignment = VerticalAlignment.Center, ToolTip = "播放进度" }; seek.SetBinding(RangeBase.MaximumProperty, new Binding("Duration")); void Restore() => seek.SetBinding(RangeBase.ValueProperty, new Binding("Position") { Mode = BindingMode.OneWay }); Restore(); Grid.SetColumn(seek, 1); progress.Children.Add(seek); bool dragging = false, dragRelease = false;
        seek.AddHandler(Thumb.DragStartedEvent, new DragStartedEventHandler((_, _) => { dragging = true; dragRelease = false; BindingOperations.ClearBinding(seek, RangeBase.ValueProperty); })); seek.AddHandler(Thumb.DragCompletedEvent, new DragCompletedEventHandler((_, _) => { vm.Seek(seek.Value); dragging = false; dragRelease = true; Restore(); })); seek.PreviewMouseLeftButtonUp += (_, _) => { if (!dragging && !dragRelease) { vm.Seek(seek.Value); Restore(); } dragRelease = false; }; seek.PreviewKeyUp += (_, e) => { if (e.Key is Key.Left or Key.Right or Key.Home or Key.End) { vm.Seek(seek.Value); Restore(); } };
        var controls = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center }; var previous = MakeIcon("\uE892", "上一首", null, 48, 27); previous.Command = vm.PreviousCommand; previous.Margin = new Thickness(0, 0, 22, 0); controls.Children.Add(previous);
        var play = MakeIcon("", "播放 / 暂停", null, 62, 29); play.Command = vm.ToggleCommand; play.SetBinding(ContentProperty, new Binding("PlayIcon")); var circle = new FrameworkElementFactory(typeof(Border), "PlaySurface"); circle.SetValue(Border.CornerRadiusProperty, new CornerRadius(32)); circle.SetValue(Border.BorderThicknessProperty, new Thickness(1)); circle.SetResourceReference(Border.BorderBrushProperty, "TextBrush"); circle.SetValue(Border.BackgroundProperty, Brushes.Transparent); var mark = new FrameworkElementFactory(typeof(System.Windows.Shapes.Path), "PlaybackMark"); mark.SetValue(System.Windows.Shapes.Path.DataProperty, Geometry.Parse("M 7,3 L 7,29 L 29,16 Z")); mark.SetValue(System.Windows.Shapes.Path.StretchProperty, Stretch.Uniform); mark.SetValue(FrameworkElement.WidthProperty, 25d); mark.SetValue(FrameworkElement.HeightProperty, 28d); mark.SetValue(FrameworkElement.MarginProperty, new Thickness(4, 0, 0, 0)); mark.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); mark.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); mark.SetResourceReference(System.Windows.Shapes.Shape.FillProperty, "TextBrush"); circle.AppendChild(mark); var playTemplate = new ControlTemplate(typeof(Button)) { VisualTree = circle }; var paused = new DataTrigger { Binding = new Binding("PlayGlyph"), Value = "Ⅱ" }; paused.Setters.Add(new Setter(System.Windows.Shapes.Path.DataProperty, Geometry.Parse("M 4,3 L 11,3 L 11,29 L 4,29 Z M 21,3 L 28,3 L 28,29 L 21,29 Z"), "PlaybackMark")); paused.Setters.Add(new Setter(FrameworkElement.MarginProperty, new Thickness(0), "PlaybackMark")); playTemplate.Triggers.Add(paused); var hover = new Trigger { Property = IsMouseOverProperty, Value = true }; hover.Setters.Add(new Setter(Border.BackgroundProperty, new DynamicResourceExtension("HoverBrush"), "PlaySurface")); playTemplate.Triggers.Add(hover); var focus = new Trigger { Property = IsKeyboardFocusedProperty, Value = true }; focus.Setters.Add(new Setter(Border.BorderBrushProperty, new DynamicResourceExtension("AccentBrush"), "PlaySurface")); playTemplate.Triggers.Add(focus); play.Template = playTemplate; controls.Children.Add(play);
        var next = MakeIcon("\uE893", "下一首", null, 48, 27); next.Command = vm.NextCommand; next.Margin = new Thickness(22, 0, 0, 0); controls.Children.Add(next); Grid.SetRow(controls, 1); footer.Children.Add(controls);
        var mode = MakeIcon("", "切换播放模式", null, 40, 22); mode.Command = vm.ModeCommand; mode.SetBinding(ContentProperty, new Binding("ModeIcon")); mode.SetBinding(ToolTipProperty, new Binding("ModeText")); mode.HorizontalAlignment = HorizontalAlignment.Left; mode.VerticalAlignment = VerticalAlignment.Center; Grid.SetRow(mode, 1); footer.Children.Add(mode);
        var utilities = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center, HorizontalAlignment = HorizontalAlignment.Right }; var mute = MakeIcon("\uE767", "静音", null, 36, 21); mute.Command = vm.MuteCommand; utilities.Children.Add(mute); var volume = new Slider { Minimum = 0, Maximum = 100, Width = 95, Margin = new Thickness(6, 0, 15, 0), VerticalAlignment = VerticalAlignment.Center, ToolTip = "音量" }; volume.SetBinding(RangeBase.ValueProperty, new Binding("Volume") { Mode = BindingMode.TwoWay }); utilities.Children.Add(volume);
        var queue = MakeIcon("\uE8F1", "播放队列", null, 40, 22); utilities.Children.Add(queue); Grid.SetRow(utilities, 1); footer.Children.Add(utilities);
        var queueList = new ListBox { ItemsSource = vm.Queue, ItemTemplate = (DataTemplate)Application.Current.Resources["TrackTemplate"], BorderThickness = new Thickness(0), MaxHeight = 380 }; var popupSurface = UiFactory.Card("播放队列", queueList); popupSurface.Margin = new Thickness(0); popupSurface.Width = 310; var popup = new Popup { Child = popupSurface, PlacementTarget = queue, Placement = PlacementMode.Top, AllowsTransparency = true, StaysOpen = false }; queue.Click += (_, _) => popup.IsOpen = !popup.IsOpen; queueList.MouseDoubleClick += (_, _) => { if (queueList.SelectedItem is Track track) { int index = vm.Queue.IndexOf(track); if (index >= 0) vm.Run(() => vm.PlayAsync(index)); } }; queueList.PreviewKeyDown += (_, e) => { if (e.Key == Key.Escape) { popup.IsOpen = false; e.Handled = true; } };
        WindowAppearance.Attach(this); PreviewKeyDown += (_, e) => { if (e.Key == Key.Escape && !popup.IsOpen) { Close(); e.Handled = true; } };
        Closed += (_, _) => { popup.IsOpen = false; Theme.Updated -= UpdateTheme; var app = (App)Application.Current; if (!app.Exiting) app.ShowMain(); };
    }
    private static Button MakeIcon(string glyph, string tip, Action? action, double size, double font)
    {
        var button = new Button { Content = glyph, ToolTip = tip, Width = size, Height = size, Padding = new Thickness(0), Margin = new Thickness(0), FontSize = font }; button.SetResourceReference(StyleProperty, "IconButton"); if (action != null) button.Click += (_, _) => action(); return button;
    }
    private static TextBlock Time(string binding, HorizontalAlignment alignment) { var text = new TextBlock { FontSize = 11, HorizontalAlignment = alignment, VerticalAlignment = VerticalAlignment.Center }; text.SetBinding(TextBlock.TextProperty, new Binding(binding)); text.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); return text; }
}
