using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using FontFamily = System.Windows.Media.FontFamily;

namespace ChiliMusic;

internal sealed class ImmersiveWindow : Window
{
    internal Popup QueuePopup { get; }
    internal ListBox QueueList { get; }
    internal LyricsView Lyrics { get; }
    internal PlaybackSeekSlider SeekSlider { get; }
    internal ImmersiveWindow(PlayerViewModel vm)
    {
        Title = "chilimusic · 正在播放"; Width = Math.Min(1100, SystemParameters.WorkArea.Width - 20); Height = Math.Min(760, SystemParameters.WorkArea.Height - 20); MinWidth = 860; MinHeight = 600;
        DataContext = vm; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; WindowStartupLocation = WindowStartupLocation.CenterScreen; ResizeMode = ResizeMode.CanResize;
        SetResourceReference(ForegroundProperty, "TextBrush"); SetResourceReference(FontFamilyProperty, "AppFont");
        WindowChrome.SetWindowChrome(this, new() { CaptionHeight = 44, ResizeBorderThickness = new Thickness(6), GlassFrameThickness = new Thickness(0), UseAeroCaptionButtons = false });
        var frame = new Border { CornerRadius = new CornerRadius(10), BorderThickness = new Thickness(1) }; frame.SetResourceReference(Border.BackgroundProperty, "BackgroundBrush"); frame.SetResourceReference(Border.BorderBrushProperty, "BorderBrush");
        var root = new Grid(); frame.Child = root; Content = frame;
        var backdrop = new System.Windows.Controls.Image { Stretch = Stretch.UniformToFill, Opacity = 1, CacheMode = new BitmapCache(), Effect = new BlurEffect { Radius = 38, RenderingBias = RenderingBias.Performance }, IsHitTestVisible = false }; backdrop.SetBinding(System.Windows.Controls.Image.SourceProperty, new Binding("Cover")); root.Children.Add(backdrop);
        var shade = new Border { IsHitTestVisible = false }; shade.SetResourceReference(Border.BackgroundProperty, "BackgroundBrush"); root.Children.Add(shade);
        void UpdateTheme() => shade.Opacity = Theme.IsDark ? .60 : .70;
        Theme.Updated += UpdateTheme; UpdateTheme();
        var layout = new Grid(); layout.RowDefinitions.Add(new() { Height = new GridLength(44) }); layout.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); layout.RowDefinitions.Add(new() { Height = new GridLength(120) }); root.Children.Add(layout);
        var header = new Grid { Margin = new Thickness(16, 0, 10, 0) }; header.ColumnDefinitions.Add(new() { Width = new GridLength(130) }); header.ColumnDefinitions.Add(new() { Width = new GridLength(1, GridUnitType.Star) }); header.ColumnDefinitions.Add(new() { Width = new GridLength(130) }); layout.Children.Add(header);
        var back = new Button { Width = 78, Height = 34, HorizontalAlignment = HorizontalAlignment.Left, Padding = new Thickness(0), Margin = new Thickness(0), ToolTip = "返回音乐库 · Esc" }; back.SetResourceReference(StyleProperty, "IconButton"); back.SetResourceReference(FontFamilyProperty, "AppFont");
        var backLabel = new StackPanel { Orientation = Orientation.Horizontal }; backLabel.Children.Add(new TextBlock { Text = "\uE76B", FontFamily = new FontFamily("Segoe MDL2 Assets"), FontSize = 12, Margin = new Thickness(0, 0, 10, 0), VerticalAlignment = VerticalAlignment.Center }); backLabel.Children.Add(new TextBlock { Text = "返回", FontSize = 12, VerticalAlignment = VerticalAlignment.Center }); back.Content = backLabel; back.Click += (_, _) => Close(); WindowChrome.SetIsHitTestVisibleInChrome(back, true); header.Children.Add(back);
        var heading = new TextBlock { Text = "正在播放", FontSize = 12, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center }; Grid.SetColumn(heading, 1); header.Children.Add(heading);
        var caption = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right, VerticalAlignment = VerticalAlignment.Center }; Grid.SetColumn(caption, 2); header.Children.Add(caption);
        foreach (var button in new[] { MakeIcon("\uE921", "最小化", () => WindowState = WindowState.Minimized, 36, 12), MakeIcon("\uE922", "最大化 / 还原", () => WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized, 36, 12), MakeIcon("\uE8BB", "关闭播放页", Close, 36, 13) }) { WindowChrome.SetIsHitTestVisibleInChrome(button, true); caption.Children.Add(button); }
        var content = new Grid { Margin = new Thickness(42, 18, 42, 4) }; content.ColumnDefinitions.Add(new() { Width = new GridLength(.43, GridUnitType.Star) }); content.ColumnDefinitions.Add(new() { Width = new GridLength(.57, GridUnitType.Star) }); Grid.SetRow(content, 1); layout.Children.Add(content);
        var record = new StackPanel { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(0, 0, 42, 0) };
        var art = new Grid { Width = 360, Height = 360 }; var note = new TextBlock { Text = "♪", FontSize = 100, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center }; note.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); art.Children.Add(note);
        var image = new Border { CornerRadius = new CornerRadius(8) }; var brush = new ImageBrush { Stretch = Stretch.UniformToFill }; BindingOperations.SetBinding(brush, ImageBrush.ImageSourceProperty, new Binding("Cover") { Source = vm }); image.Background = brush; art.Children.Add(image);
        var artwork = new Border { CornerRadius = new CornerRadius(8), BorderThickness = new Thickness(1), Child = new Viewbox { Child = art }, HorizontalAlignment = HorizontalAlignment.Center }; artwork.SetResourceReference(Border.BackgroundProperty, "SurfaceBrush"); artwork.SetResourceReference(Border.BorderBrushProperty, "BorderBrush"); record.Children.Add(artwork);
        var title = new TextBlock { TextAlignment = TextAlignment.Center, FontSize = 27, FontWeight = FontWeights.SemiBold, Margin = new Thickness(0, 20, 0, 7), TextWrapping = TextWrapping.Wrap, TextTrimming = TextTrimming.CharacterEllipsis, MaxHeight = 78 }; title.SetBinding(TextBlock.TextProperty, new Binding("Title")); title.SetBinding(ToolTipProperty, new Binding("Title")); record.Children.Add(title);
        var artist = new TextBlock { TextAlignment = TextAlignment.Center, FontSize = 15, TextTrimming = TextTrimming.CharacterEllipsis, Margin = new Thickness(0, 0, 0, 5) }; artist.SetBinding(TextBlock.TextProperty, new Binding("Artist")); record.Children.Add(artist);
        var album = new TextBlock { TextAlignment = TextAlignment.Center, FontSize = 12, TextTrimming = TextTrimming.CharacterEllipsis }; album.SetBinding(TextBlock.TextProperty, new Binding("Album")); album.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); record.Children.Add(album);
        var format = new TextBlock { FontSize = 10 }; format.SetBinding(TextBlock.TextProperty, new Binding("Current.Format")); var badge = new Border { Child = format, BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(3), Padding = new Thickness(7, 3, 7, 3), HorizontalAlignment = HorizontalAlignment.Center, Margin = new Thickness(0, 12, 0, 0) }; badge.SetResourceReference(Border.BorderBrushProperty, "AccentBrush"); badge.SetBinding(ToolTipProperty, new Binding("AudioInfo")); record.Children.Add(badge); content.Children.Add(record);
        void FitArtwork() { double size = Math.Clamp(Math.Min(record.ActualWidth, content.ActualHeight - 174), 120, 360); artwork.Width = artwork.Height = size; }
        content.SizeChanged += (_, _) => FitArtwork(); record.SizeChanged += (_, _) => FitArtwork();
        var words = new Grid(); words.RowDefinitions.Add(new() { Height = GridLength.Auto }); words.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); var tools = new LyricsToolbar(vm, true) { HorizontalAlignment = HorizontalAlignment.Right }; words.Children.Add(tools); Lyrics = new LyricsView(vm, true); Grid.SetRow(Lyrics, 1); words.Children.Add(Lyrics); Grid.SetColumn(words, 1); content.Children.Add(words);
        var footer = new Grid { Margin = new Thickness(40, 8, 40, 14) }; footer.RowDefinitions.Add(new() { Height = new GridLength(32) }); footer.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); Grid.SetRow(footer, 2); layout.Children.Add(footer);
        var progress = new Grid(); progress.RowDefinitions.Add(new() { Height = new GridLength(16) }); progress.RowDefinitions.Add(new() { Height = new GridLength(16) }); footer.Children.Add(progress);
        SeekSlider = new PlaybackSeekSlider { ToolTip = "播放进度", VerticalAlignment = VerticalAlignment.Center }; progress.Children.Add(SeekSlider);
        var elapsed = Time("PositionText", HorizontalAlignment.Left); var duration = Time("DurationText", HorizontalAlignment.Right); Grid.SetRow(elapsed, 1); Grid.SetRow(duration, 1); progress.Children.Add(elapsed); progress.Children.Add(duration);
        var controls = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center }; var previous = MakeIcon("\uE892", "上一首", null, 42, 24); previous.Command = vm.PreviousCommand; previous.Margin = new Thickness(0, 0, 12, 0); controls.Children.Add(previous);
        var play = MakeIcon("", "播放 / 暂停", null, 62, 29); play.Command = vm.ToggleCommand; play.SetBinding(ContentProperty, new Binding("PlayIcon")); var circle = new FrameworkElementFactory(typeof(Border), "PlaySurface"); circle.SetValue(Border.CornerRadiusProperty, new CornerRadius(32)); circle.SetValue(Border.BorderThicknessProperty, new Thickness(1)); circle.SetResourceReference(Border.BorderBrushProperty, "TextBrush"); circle.SetResourceReference(Border.BackgroundProperty, "TextBrush"); var mark = new FrameworkElementFactory(typeof(System.Windows.Shapes.Path), "PlaybackMark"); mark.SetValue(System.Windows.Shapes.Path.DataProperty, Geometry.Parse("M 7,3 L 7,29 L 29,16 Z")); mark.SetValue(System.Windows.Shapes.Path.StretchProperty, Stretch.Uniform); mark.SetValue(FrameworkElement.WidthProperty, 25d); mark.SetValue(FrameworkElement.HeightProperty, 28d); mark.SetValue(FrameworkElement.MarginProperty, new Thickness(4, 0, 0, 0)); mark.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); mark.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); mark.SetResourceReference(System.Windows.Shapes.Shape.FillProperty, "BackgroundBrush"); circle.AppendChild(mark); var playTemplate = new ControlTemplate(typeof(Button)) { VisualTree = circle }; var paused = new DataTrigger { Binding = new Binding("PlayGlyph"), Value = "Ⅱ" }; paused.Setters.Add(new Setter(System.Windows.Shapes.Path.DataProperty, Geometry.Parse("M 4,3 L 11,3 L 11,29 L 4,29 Z M 21,3 L 28,3 L 28,29 L 21,29 Z"), "PlaybackMark")); paused.Setters.Add(new Setter(FrameworkElement.MarginProperty, new Thickness(0), "PlaybackMark")); playTemplate.Triggers.Add(paused); var hover = new Trigger { Property = IsMouseOverProperty, Value = true }; hover.Setters.Add(new Setter(UIElement.OpacityProperty, .82, "PlaySurface")); playTemplate.Triggers.Add(hover); var focus = new Trigger { Property = IsKeyboardFocusedProperty, Value = true }; focus.Setters.Add(new Setter(Border.BorderBrushProperty, new DynamicResourceExtension("AccentBrush"), "PlaySurface")); playTemplate.Triggers.Add(focus); play.Template = playTemplate; controls.Children.Add(play);
        var next = MakeIcon("\uE893", "下一首", null, 42, 24); next.Command = vm.NextCommand; next.Margin = new Thickness(12, 0, 0, 0); controls.Children.Add(next); Grid.SetRow(controls, 1); footer.Children.Add(controls);
        var mode = MakeIcon("", "切换播放模式", null, 36, 20); mode.Command = vm.ModeCommand; mode.SetBinding(ContentProperty, new Binding("ModeIcon")); mode.SetBinding(ToolTipProperty, new Binding("ModeText")); mode.Margin = new Thickness(0, 0, 12, 0); controls.Children.Insert(0, mode);
        var favorite = MakeIcon("", "收藏 / 取消收藏", null, 36, 24); favorite.FontFamily = new FontFamily("Segoe UI Symbol"); favorite.Command = vm.FavoriteCommand; favorite.SetBinding(ContentProperty, new Binding("FavoriteGlyph")); favorite.SetResourceReference(ForegroundProperty, "AccentBrush"); favorite.Margin = new Thickness(12, 0, 0, 0); controls.Children.Add(favorite);
        var utilities = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center, HorizontalAlignment = HorizontalAlignment.Right }; var mute = MakeIcon("\uE767", "静音", null, 36, 21); mute.Command = vm.MuteCommand; utilities.Children.Add(mute); var volume = new Slider { Minimum = 0, Maximum = 100, Width = 78, Margin = new Thickness(5, 0, 8, 0), VerticalAlignment = VerticalAlignment.Center, ToolTip = "音量" }; volume.SetBinding(RangeBase.ValueProperty, new Binding("Volume") { Mode = BindingMode.TwoWay }); utilities.Children.Add(volume);
        var queue = MakeIcon("\uE8F1", "播放队列", null, 40, 22); utilities.Children.Add(queue); Grid.SetRow(utilities, 1); footer.Children.Add(utilities);
        QueueList = new ListBox { ItemsSource = vm.Queue, ItemTemplate = (DataTemplate)Application.Current.Resources["TrackTemplate"], BorderThickness = new Thickness(0), Height = 280, Background = Brushes.Transparent }; QueueList.SetResourceReference(FontFamilyProperty, "AppFont"); QueueList.SetResourceReference(ForegroundProperty, "TextBrush");
        var queueBody = new Grid(); queueBody.RowDefinitions.Add(new() { Height = GridLength.Auto }); queueBody.RowDefinitions.Add(new() { Height = new GridLength(1, GridUnitType.Star) }); var queueHeading = new TextBlock { FontSize = 13, FontWeight = FontWeights.SemiBold, Margin = new Thickness(2, 0, 0, 12) }; queueHeading.SetBinding(TextBlock.TextProperty, new Binding("Queue.Count") { Source = vm, StringFormat = "播放队列 · {0}" }); queueBody.Children.Add(queueHeading);
        var queueContent = UiFactory.ListWithEmptyState(QueueList, "队列为空", "添加歌曲后会显示在这里。"); Grid.SetRow(queueContent, 1); queueBody.Children.Add(queueContent);
        var popupSurface = new Border { Child = queueBody, Width = 330, CornerRadius = new CornerRadius(10), BorderThickness = new Thickness(1), Padding = new Thickness(14), Margin = new Thickness(0, 0, 0, 12) }; popupSurface.SetResourceReference(Border.BackgroundProperty, "SurfaceBrush"); popupSurface.SetResourceReference(Border.BorderBrushProperty, "BorderBrush"); popupSurface.SetResourceReference(TextElement.FontFamilyProperty, "AppFont"); popupSurface.SetResourceReference(TextElement.ForegroundProperty, "TextBrush");
        QueuePopup = new Popup { Child = popupSurface, PlacementTarget = queue, Placement = PlacementMode.Top, AllowsTransparency = true, StaysOpen = false }; queue.Click += (_, _) => QueuePopup.IsOpen = !QueuePopup.IsOpen; QueuePopup.Opened += (_, _) => { QueueList.SelectedItem = vm.Current; if (vm.Current != null) QueueList.ScrollIntoView(vm.Current); };
        void PlaySelected() { if (QueueList.SelectedItem is Track track) { int index = vm.Queue.IndexOf(track); if (index >= 0) vm.Run(() => vm.PlayAsync(index)); } }
        QueueList.MouseDoubleClick += (_, _) => PlaySelected(); QueueList.PreviewKeyDown += (_, e) => { if (e.Key == Key.Escape) { QueuePopup.IsOpen = false; e.Handled = true; } else if (e.Key == Key.Enter) { PlaySelected(); e.Handled = true; } };
        WindowAppearance.Attach(this); PreviewKeyDown += (_, e) => { if (e.Key == Key.Escape) { if (QueuePopup.IsOpen) QueuePopup.IsOpen = false; else Close(); e.Handled = true; } };
        Closed += (_, _) => { QueuePopup.IsOpen = false; Theme.Updated -= UpdateTheme; var app = (App)Application.Current; if (!app.Exiting) app.ShowMain(); };
    }
    private static Button MakeIcon(string glyph, string tip, Action? action, double size, double font)
    {
        var button = new Button { Content = glyph, ToolTip = tip, Width = size, Height = size, Padding = new Thickness(0), Margin = new Thickness(0), FontSize = font }; button.SetResourceReference(StyleProperty, "IconButton"); if (action != null) button.Click += (_, _) => action(); return button;
    }
    private static TextBlock Time(string binding, HorizontalAlignment alignment) { var text = new TextBlock { FontSize = 11, HorizontalAlignment = alignment, VerticalAlignment = VerticalAlignment.Center }; text.SetBinding(TextBlock.TextProperty, new Binding(binding)); text.SetResourceReference(TextBlock.ForegroundProperty, "MutedBrush"); return text; }
}
